spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: username
      password: password
      database: ecommerce_transactions
      authentication-database: admin
  kafka:
    bootstrap-servers: localhost:9093

management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true