spring:
  data:
    mongodb:
      host: mongo-container
      port: 27017
      username: username
      password: password
      database: ecommerce_transactions
      authentication-database: admin