spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: username
      password: password
      database: ecommerce_transactions
      authentication-database: admin
      auto-index-creation: true
  kafka:
    bootstrap-servers: localhost:9093

management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true

resilience4j.circuitbreaker:
  instances:
    purchaseOrderConsumer:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 10000ms
      failureRateThreshold: 50
